# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Install ffmpeg for audio/video processing
RUN apt-get update \
    && apt-get install -y ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN pip install --no-cache-dir .

# Expose port
EXPOSE 8080

# Launch MCP server
CMD ["douyin-mcp-server", "--host", "0.0.0.0", "--port", "8080"]
